### PR TITLE
Allow setting GIT_VERSION

### PR DESCRIPTION
**Pull request by orbea**

### CODE REVIEW

**Comment by Sir-Walrus** [comment]
I think ?= defaults to =, not :=, if the variable isn't set.

Not sure if it matters. Probably doesn't.

**Comment by orbea** [comment]
It does matter for my slackbuild scripts as it does for ubuntu/debian.

Please see the discussion here.
https://github.com/libretro/libretro-2048/pull/21

**Comment by Sir-Walrus** [comment]
That's not what I'm asking about, I'm asking about the lazy vs eager evaluation of = vs :=.

I'm pretty sure ?= is ignored if there's a command line argument, anyways. Maybe different make implementations or versions behave differently.

**Comment by orbea** [comment]
Yea, exactly. Its a very small nitpick, but being able to avoid the following seems worth it to me if its so easy. Thanks for the merge. :)
```
fatal: Not a git repository (or any parent up to mount point /tmp)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Pull request merged**
